import { Patch } from '@/lib/types';
import { Copy, Download } from 'lucide-react';
import ReactDiffViewer, { DiffMethod } from 'react-diff-viewer-continued';

interface PatchDiffProps {
  patch: Patch;
}

export default function PatchDiff({ patch }: PatchDiffProps) {
  const copyToClipboard = () => {
    navigator.clipboard.writeText(patch.diffUnified);
    alert('Patch copied to clipboard!');
  };

  // Simple parser to split unified diff into old/new for the viewer
  // Note: react-diff-viewer expects old/new text, but we have a unified diff.
  // For simplicity in this demo without a heavy parser, we'll just render the unified diff text 
  // or use a unified diff view if the library supports it directly or we parse it.
  // react-diff-viewer-continued is good for side-by-side.
  // If we only have the unified diff string, we might just render it nicely with syntax highlighting 
  // or use a simpler approach if we don't want to parse it back to original/new files.
  // Let's try to render it as a raw unified diff with coloring for now if we can't easily reconstruct.
  // Actually, let's just render the raw diff with custom styling as requested in "Performance & scale considerations"
  // "parse unified diff into hunks and render two columns... OR render unified diff text"
  
  const lines = patch.diffUnified.split('\n');

  return (
    <div className="border border-white/20 rounded-lg overflow-hidden bg-[#1e1e1e]" aria-label={`Patch diff for ${patch.file}`}>
      <div className="flex items-center justify-between px-4 py-2 bg-white/5 border-b border-white/10">
        <span className="font-mono text-sm text-neonCyan">{patch.file}</span>
        <div className="flex gap-2">
          <button 
            onClick={copyToClipboard}
            className="p-2 hover:bg-white/10 rounded transition-colors"
            title="Copy Patch"
          >
            <Copy size={16} />
          </button>
          <button className="p-2 hover:bg-white/10 rounded transition-colors" title="Download">
            <Download size={16} />
          </button>
        </div>
      </div>
      
      <div className="p-4 overflow-x-auto font-mono text-sm">
        {lines.map((line, i) => {
          let className = "text-gray-400";
          if (line.startsWith('+')) className = "text-green-400 bg-green-900/20 block w-full";
          if (line.startsWith('-')) className = "text-red-400 bg-red-900/20 block w-full";
          if (line.startsWith('@@')) className = "text-purple-400 block w-full my-2";
          
          return (
            <div key={i} className={className}>
              <span className="inline-block w-8 opacity-30 select-none text-right mr-4">{i + 1}</span>
              {line}
            </div>
          );
        })}
      </div>
      
      <div className="px-4 py-2 bg-white/5 border-t border-white/10 text-xs text-gray-500">
        Generated by {patch.generatedBy}
      </div>
    </div>
  );
}
