<# CVA Pre-commit Hook Installer

Installs the CVA security scanning pre-commit hook for Git.

Usage:
    .\install_hooks.ps1           # Install hook
    .\install_hooks.ps1 -Remove   # Remove hook
    .\install_hooks.ps1 -Test     # Test the hook manually
#>

param(
    [switch]$Remove,
    [switch]$Test,
    [string]$RepoPath = "."
)

$ErrorActionPreference = "Stop"

# Resolve repository path
$RepoRoot = Resolve-Path $RepoPath
$HooksDir = Join-Path $RepoRoot ".git\hooks"
$HookPath = Join-Path $HooksDir "pre-commit"
$PythonPath = Join-Path (Split-Path $RepoRoot -Parent) ".venv\Scripts\python.exe"

Write-Host ""
Write-Host "╔═══════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║  CVA PRE-COMMIT HOOK INSTALLER                             ║" -ForegroundColor Cyan
Write-Host "╚═══════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

# Test mode
if ($Test) {
    Write-Host "Running pre-commit check manually..." -ForegroundColor Cyan
    Set-Location $RepoRoot
    & $PythonPath -m modules.monitoring.precommit_hook --check
    exit $LASTEXITCODE
}

# Remove mode
if ($Remove) {
    if (Test-Path $HookPath) {
        Remove-Item $HookPath -Force
        Write-Host "Pre-commit hook removed successfully!" -ForegroundColor Green
    } else {
        Write-Host "No pre-commit hook found." -ForegroundColor Yellow
    }
    exit 0
}

# Verify paths
if (-not (Test-Path $HooksDir)) {
    Write-Host "Error: .git/hooks directory not found at $HooksDir" -ForegroundColor Red
    Write-Host "Make sure you're in a git repository." -ForegroundColor Yellow
    exit 1
}

if (-not (Test-Path $PythonPath)) {
    Write-Host "Error: Python not found at $PythonPath" -ForegroundColor Red
    exit 1
}

# Check for existing hook
if (Test-Path $HookPath) {
    $content = Get-Content $HookPath -Raw
    if ($content -notmatch "CVA Pre-commit") {
        Write-Host "Warning: A different pre-commit hook already exists." -ForegroundColor Yellow
        $response = Read-Host "Overwrite? (y/N)"
        if ($response -ne 'y') {
            Write-Host "Installation cancelled." -ForegroundColor Gray
            exit 0
        }
    }
}

# Create hook script (bash format for Git Bash on Windows)
$hookContent = @"
#!/bin/sh
# CVA Pre-commit Security Hook
# Auto-generated by install_hooks.ps1
# Bypassing: git commit --no-verify

# Navigate to repo root
cd "`$(git rev-parse --show-toplevel)" || exit 1

# Run the Python pre-commit checker
"$PythonPath" -m modules.monitoring.precommit_hook --check

# Capture and return exit code
exit_code=`$?
exit `$exit_code
"@

# Write hook file
try {
    Set-Content -Path $HookPath -Value $hookContent -Encoding UTF8 -NoNewline
    Write-Host "Pre-commit hook installed successfully!" -ForegroundColor Green
    Write-Host ""
    Write-Host "Configuration:" -ForegroundColor White
    Write-Host "  Hook:   $HookPath"
    Write-Host "  Python: $PythonPath"
    Write-Host ""
    Write-Host "The hook will automatically scan staged files before each commit." -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Commands:" -ForegroundColor White
    Write-Host "  Test hook:    .\install_hooks.ps1 -Test"
    Write-Host "  Remove hook:  .\install_hooks.ps1 -Remove"
    Write-Host "  Bypass once:  git commit --no-verify"
    Write-Host ""
} catch {
    Write-Host "Error installing hook: $_" -ForegroundColor Red
    exit 1
}
